### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by blazpavlica** [ReaCoMa/ReaCoMa-2.0#22] opened 2023-08-07 16:45 UTC
I used the scripts a few months ago, today when I run, I get this error:

```
D:\RIP\medvešček\A1-001-glued piščal pekli-glued_nmf_214538903009241.wav failed to be made by the command line.
stack traceback:
	D:\RIP\ReaCoMa 2.0\lib/utils.lua:122: in function 'utils.assert'
	D:\RIP\ReaCoMa 2.0\lib/layers.lua:13: in function 'layers.exist'
	D:\RIP\ReaCoMa 2.0\lib/layers.lua:43: in function 'layers.process_all_items'
	D:\RIP\ReaCoMa 2.0\lib/algorithms/nmf.lua:38: in function 'algorithms/nmf.perform_update'
	D:\RIP\ReaCoMa 2.0\lib/imgui_helpers.lua:94: in function 'imgui_helpers.process'
	D:\RIP\ReaCoMa 2.0\lib/imgui_wrapper.lua:31: in function 'imgui_wrapper.loop'
	D:\RIP\ReaCoMa 2.0\lib/imgui_wrapper.lua:110: in function <D:\RIP\ReaCoMa 2.0\lib/imgui_wrapper.lua:109>
```

**Comment by jamesb93** [comment] 2023-08-07 17:10
Which version are you using?

**Comment by blazpavlica** [comment] 2023-08-07 19:33
Hi, it version 2. I downloaded the latest release and updated Reaper. Now I get a different error:
`D:\RIP\ReaCoMa 2.0\lib/utils.lua:16: attempt to index a nil value (field 'debug')`
```
D:\RIP\medvešček\A1-001-glued_nmf_215533437567841.wav failed to be made by the command line.

The most recent CLI call was:

"D:\RIP\ReaCoMa 2.0\bin/fluid-nmf" -source "D:\RIP\medvešček\A1-001-glued.wav" -resynth "D:\RIP\medvešček\A1-001-glued_nmf_215533437567841.wav" -resynthmode 1 -iterations 253 -components 2 -fftsettings 1024 512 1024 -1 -numframes 1181711 -startframe 32422172
```
Does this help?

**Comment by jamesb93** [comment] 2023-08-07 20:35
A little! What is the "latest"? Which release?

**Comment by blazpavlica** [comment] 2023-08-07 20:46
ReaCoMa: 2.9.0, Reaper: 6.81
Let me know if you need any other test.

**Comment by jamesb93** [comment] 2023-08-07 20:49
Then it seems you found a bug :)

I have a few features in the works anyway and I've been hankering to make a release. If I give you a pre-release beta can you take it for a spin for me? Should be in the next day, maybe this evening Berlin time?

**Comment by blazpavlica** [comment] 2023-08-07 20:51
Sure, happy to help. :)

**Comment by jamesb93** [comment] 2023-08-07 22:47
https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.10

Can you try this one for me @blazpavlica?

**Comment by blazpavlica** [comment] 2023-08-09 07:43
I ran it and I get this:

`configuration.lua:8: cannot open file 'C:\Users\Blazen\AppData\Roaming\REAPER/Scripts/reacoma.ini' (No such file or directory)`

Did I forget to install something?

**Comment by jamesb93** [comment] 2023-08-09 08:29
No you found an oversight by me. I've changed to making it possible to use a `.ini` file to configure reacoma going forward, but it shouldn't bail if it doesn't exist and should gracefully continue. I'll fix this now...

**Comment by jamesb93** [comment] 2023-08-09 08:55
Can you try this new build? Same tag / version but I updated that function.

https://github.com/ReaCoMa/ReaCoMa-2.0/releases/tag/2.10

**Comment by jamesb93** [comment] 2023-08-10 13:34
Okay. This is actually a good thing because we are now at a state where the problem is only a few things.

The failure to create the output file can be a number of things. The best way to test is for you to supply me with the file and see if it works here. That will tell us where the problem exists.

**Comment by blazpavlica** [comment] 2023-08-15 13:49
Hey, sorry for late response, here is the file: https://we.tl/t-BAOqMEKIzC

To be sure, I checked in another project with two other files and it worked. So it is only this file.

**Comment by jamesb93** [comment] 2024-07-07 11:28
If you're still encountering this issue let me know and we can try to fix. Otherwise going to close this. Sorry we couldn't resolve it but I was unable to diagnose it locally.

**Closed by jamesb93** 2024-07-07 11:28 UTC

**Comment by blazERpavlica** [comment] 2024-07-07 18:11
Hi, I have encountered the problem once again a while ago and I was able to solve it by encoding the wav with different bit rate and other settings. I didn't go deep into it to see which settings worked and which don't, I just used whatever worked. Sorry I forgot to report.

**Comment by jamesb93** [comment] 2024-07-07 20:21
Thanks! Maybe the WAV reading in the underlying HISSTools library faced a very ambiguous format. This sometimes happens with WAV that extends the header format arbitrarily.
